---
title: "Life"
author: "Jessica Wu"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(scales)
library(ggthemes)
library(lubridate)
library(tidyverse)
```

```{r bread}
bread <- read_csv("data-sources/bread.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `bread recipe: (United States)` = col_double()
)) %>%
  rename(bread = `bread recipe: (United States)`) %>%
  mutate(bread = bread / 16 * 100)
```

```{r hair}
hair <- read_csv("data-sources/hair.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `how to cut your own hair: (United States)` = col_double()
)) %>%
  rename(hair = `how to cut your own hair: (United States)`) %>%
  mutate(hair = hair / 4 * 100)
```

```{r dalgona coffee, include=FALSE}
dalgona <- read_csv("data-sources/dalgona.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `dalgona coffee: (United States)` = col_double()
)) %>%
  rename(dalgona = `dalgona coffee: (United States)`) %>%
  mutate(dalgona = dalgona * 100)

```

```{r boredom}

boredom <- read_csv("data-sources/boredom.csv",
                    skip = 1,
                    col_types = cols(
  Day = col_date(format = ""),
  `boredom: (United States)` = col_double()
)) %>%
  rename(boredom = `boredom: (United States)`) %>%
  mutate(boredom = boredom / 5 * 100)
```

On Tuesday, March 10th, 2020, Harvard College students were instructed to move 
out of their dorms in 5 days. Here's how life patterns have changed since then.
```{r}

home_life <- boredom %>%
  left_join(dalgona, by = "Day") %>%
  left_join(hair, by = "Day") %>%
  left_join(bread, by = "Day") %>%
  tail(-44) %>%
  rename(date = Day) %>%
  pivot_longer(-date, names_to = "search", values_to = "frequency")

events <- tibble(time = c(ymd(20200314),
                              ymd(20200317),
                              ymd(20200321)),
                     text = c('Harvard College students must move out by today',
                              'Trump announces "15 days to slow the spread" plan',
                              'Governor Cuomo issues stay-at-home order for NY'))

life_search_terms <- home_life %>%
  ggplot() +
  geom_line(aes(x = date, y = frequency, color = search)) + 
  geom_vline(xintercept=as.numeric(home_life$date[c(24, 25, 49)]),
                linetype=2, colour="black") +
  theme_calc() +
  labs(title = "What are people doing while at home?",
       subtitle = "Taking a look a Google Search trends",
       y = "Percent (%) Frequency of Search \n\ Relative to Itself on March 10th",
       x = "Date") +
  scale_color_discrete(name = "Search Term", labels = c('"boredom"',
                                                        '"bread recipe"',
                                                        '"dalgona coffee"',
                                                        '"how to cut your own hair"')) +
  geom_text(data = events, mapping = aes(label = text, y = 700, x = time), 
            angle = 90,
            hjust = -0.20,
            size = 3)
```

```{r}
life_search_terms
```

