---
title: "Love"
author: "Jessica Wu"
date: "4/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(lubridate)
library(ggthemes)
library(tidyverse)
```

How is the face of love changing during quarantine?

### Long distance relationships

```{r long distance}

long_dist <- read_csv("data-sources/longdistance.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `Long-distance relationship: (United States)` = col_double()
)) %>%
  rename(long_dist = `Long-distance relationship: (United States)`) %>%
  tail(-44) %>%
  mutate(long_dist = long_dist / 42 * 100)

events <- tibble(time = c(ymd(20200314),
                              ymd(20200317),
                              ymd(20200321)),
                     text = c('Harvard College students must move out by today',
                              'Trump announces "15 days to slow the spread" plan',
                              'Governor Cuomo issues stay-at-home order for NY'))

ggplot(long_dist, aes(x = Day, y = long_dist)) +
  geom_line(color = "light blue") +
  labs(
    title = "Interest in Long-Distance Relationships During Social Distancing",
    subtitle = "Taking a look at Google Search Trends",
    y = "Popularity of the Topic, 'Long Distance', \n\ Relative to March 10th (%)",
    x = "Date"
  ) +
  geom_vline(xintercept=as.numeric(long_dist$Day[c(6, 7, 13)]),
                linetype=2, colour="black") +
  geom_text(data = events, mapping = aes(label = text, y = 0, x = time), 
            angle = 90,
            hjust = -0.20,
            size = 3) +
  theme_calc()
```

### Divorce and Legal Separation
```{r divorce}

divorce <- read_csv("data-sources/divorce.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `Divorce: (United States)` = col_double()
)) %>%
  rename(divorce = `Divorce: (United States)`) %>%
  mutate(divorce = divorce / 82 * 100)
  
```

```{r divorce lawyer}
divorce_lawyer <- read_csv("data-sources/divorcelawyer.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `divorce lawyer: (United States)` = col_double()
)) %>%
  rename(divorce_lawyer = `divorce lawyer: (United States)`) %>%
  mutate(divorce_lawyer = divorce_lawyer / 79 * 100)
```

```{r legal separation}

legal_sep <- read_csv("data-sources/legalseparation.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `Legal separation: (United States)` = col_double()
)) %>%
  rename(legal_sep = `Legal separation: (United States)`) %>%
  mutate(legal_sep = legal_sep / 56 * 100)

```

```{r divorce search terms}

divorce_terms <- divorce %>%
  left_join(divorce_lawyer, by = "Day") %>%
  left_join(legal_sep, by = "Day") %>%
  tail(-44) %>%
  rename(date = Day) %>%
  pivot_longer(-date, names_to = "search", values_to = "frequency")

events <- tibble(time = c(ymd(20200314),
                              ymd(20200317),
                              ymd(20200321)),
                     text = c('Harvard College students must move out by today',
                              'Trump announces "15 days to slow the spread" plan',
                              'Governor Cuomo issues stay-at-home order for NY'))

divorce_search_terms <- divorce_terms %>%
  ggplot() +
  geom_line(aes(x = date, y = frequency, color = search)) + 
  geom_vline(xintercept=as.numeric(divorce_terms$date[c(18, 19, 37)]),
                linetype=2, colour="black") +
  theme_calc() +
  labs(title = "How are people feeling about their marriages?",
       subtitle = "Taking a look a Google Search trends",
       y = "Percent (%) Frequency of Search \n\ Relative to Itself on March 10th",
       x = "Date") +
  scale_color_discrete(name = "Searches", labels = c('Topic: Divorce',
                                                        'Term: "divorce lawyer"',
                                                        'Topic: Legal separation')) +
  geom_text(data = events, mapping = aes(label = text, y = 0, x = time), 
            angle = 90,
            hjust = -0.20,
            size = 3)

divorce_search_terms

```


### Domestic Violence
Lots of people have suggested that people are facing increased domestic violence
under stay-at-home orders. I looked to Google Search trends to see if this was
possibly captured by
```{r domestic violence}

dom_violence <- read_csv("data-sources/domesticviolence.csv",
         skip = 1,
         col_types = cols(
  Day = col_date(format = ""),
  `domestic violence: (United States)` = col_double()
)) %>%
  rename(dom_violence = `domestic violence: (United States)`) %>%
  tail(-44) %>%
  mutate(dom_violence = dom_violence / 78 * 100)

ggplot(dom_violence, aes(x = Day, y = dom_violence)) +
  geom_line(color = "red") +
  labs(
    title = "Interest in Domestic Violence During Social Distancing",
    subtitle = "Taking a look at Google Search Trends",
    y = "Popularity of the Topic, 'Domestic Violence', \n\ Relative to March 10th (%)",
    x = "Date"
  ) +
  geom_vline(xintercept=as.numeric(long_dist$Day[c(6, 7, 13)]),
                linetype=2, colour="black") +
  geom_text(data = events, mapping = aes(label = text, y = 50, x = time), 
            angle = 90,
            hjust = -0.20,
            size = 3) +
  theme_calc()

```

